# Generated by Django 2.2 on 2019-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_body',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_heading',
            new_name='comment_heading',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='comment_id',
        ),
    ]
